name: Coverage

on:
  push:
    branches:
      - master
      - 'test/**'
      - 'feat/**'
      - 'fix/**'
      - 'perf/**'
      - 'refactor/**'
  pull_request:
    branches:
      - master
      - 'test/**'
      - 'feat/**'
      - 'fix/**'
      - 'perf/**'
      - 'refactor/**'

jobs:
  run:
    runs-on: ubuntu-latest
    
    env:
      OS: ubuntu-latest
      PYTHON: '3.10'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: '3.10'
    - name: Generate coverage report
      run: |
        python -m pip install --upgrade pip
        pip --no-cache-dir install -r  requirements.txt
        python3 -m nltk.downloader wordnet
        python3 -m nltk.downloader punkt
        python3 -m nltk.downloader stopwords
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/reports/
        fail_ci_if_error: true
        name: codecov-umbrella
        verbose: true
