name: Coverage

on:
  push:
    branches:
      - master
      - 'test/**'
      - 'feat/**'
      - 'fix/**'
      - 'perf/**'
      - 'refactor/**'
  pull_request:
    branches:
      - master
      - 'test/**'
      - 'feat/**'
      - 'fix/**'
      - 'perf/**'
      - 'refactor/**'

jobs:
  run:
    runs-on: ubuntu-latest
    
    env:
      OS: ubuntu-latest
      PYTHON: '3.10'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: '3.10'
    - name: Generate coverage report
      run: |
        pip --no-cache-dir install -r  requirements.txt \
        && echo "import nltk" > download_nltk.py \
        && echo "nltk.download('wordnet')" >> download_nltk.py \
        && echo "nltk.download('punkt')" >> download_nltk.py \
        && echo "nltk.download('stopwords')" >> download_nltk.py \
        && echo "quit()" >> download_nltk.py \
        && python3 download_nltk.py \ 
        && rm download_nltk.py
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/reports/
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        files: ./coverage1.xml,./coverage2.xml,!./cache
        flags: unittests
        name: codecov-umbrella
        verbose: true
